### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by jungle-boogie** [Tarsnap/scrypt#150]
Hi,

Trying to update `scrypt` from git source and compile, but it's failing:

```
ibcperciva/crypto/crypto_entropy.o: In function `cpusupport_x86_rdrand':
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_present_1'
libcperciva/crypto/crypto_entropy.o: In function `update_from_rdrand':
libcperciva/crypto/crypto_entropy.c:48: undefined reference to `generate_seed_rdrand'
libcperciva/crypto/crypto_entropy.o: In function `cpusupport_x86_rdrand':
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_init_1'
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_detect_1'
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_present_1'
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_init_1'
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_present_1'
libcperciva/crypto/crypto_entropy.o: In function `update_from_rdrand':
libcperciva/crypto/crypto_entropy.c:48: undefined reference to `generate_seed_rdrand'
libcperciva/crypto/crypto_entropy.o: In function `cpusupport_x86_rdrand':
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_init_1'
./libcperciva/cpusupport/cpusupport.h:107: undefined reference to `cpusupport_x86_rdrand_detect_1'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (Makefile:673 'scrypt')
*** Error 1 in /home/sean/bin/scrypt (Makefile:468 'all')
```

config output: https://ptpb.pw/OqQB

**Comment by gperciva** [comment]
Did you run `autoreconf -i` before `./configure && make` ?

**Comment by gperciva** [comment]
urgh.  I'm having difficulty running autoconf on OpenBSD 6.1.  I'll update once I've figured out what environment variables and/or newer versions OpenBSD wants me to have.

**Comment by gperciva** [comment]
I managed to get it working by:
- using the automake files that were produced on a Linux machine (including `configure`)
- installing gcc 4.9.4 (instead of the 4.2.1 that was on the system)
- running `./configure CC=egcc` because `gcc` still return 4.2.1.

I'm looking into the issue with compiling scrypt with gcc 4.2.1, and then I'll take another look at autotools on OpenBSD.

**Comment by gperciva** [comment]
> And you are already calling out `autoreconf` in your BUILDING doc:
> https://github.com/Tarsnap/scrypt/blob/master/BUILDING#L39

heh, and I even specified that it needs to be 1.11.2 or higher:
https://github.com/Tarsnap/scrypt/blob/master/BUILDING#L43

I won't keep on looking at why it won't work on automake 1.9, then.  :)

**Comment by jungle-boogie** [comment]
Thanks for your quick help!
